---
title: "hexSticker"
author: "zhly"
date: "2024-01-15"
categories: [r, code, visualization, sticker]
format: html
editor: visual
---

```{r,message=FALSE}
library(hexSticker)
library(ggplot2)
library(lattice)
library(showtext)
```

# 方案一

```{r}
s <- sticker(~plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab=""),
             package="hexSticker", p_size=20, s_x=.8, s_y=.6, s_width=1.4, s_height=1.2,
             filename="./baseplot.png")
s
print(s)
```

```{r}
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
bwplot <- bwplot(counts ~ outcome | treatment, xlab=NULL, ylab=NULL, cex=.5,
                 scales=list(cex=.5), par.strip.text=list(cex=.5))
sticker(bwplot, package="DATA", p_size=20, s_x=1.05, s_y=.8, s_width=2, s_height=1.5,
        h_fill="#f9690e", h_color="#f39c12", filename="./DATA.png")
```

```{r}
p <- ggplot(aes(x = mpg, y = wt), data = mtcars) + geom_point()
p <- p + theme_void() + theme_transparent()

sticker(p, package="hexSticker", p_size=14, s_x=1, s_y=.75, s_width=1.3, s_height=1,
        filename="./ggplot2.png")
```

```{r}
## Loading Google fonts (http://www.google.com/fonts)
font_add_google("Gochi Hand", "gochi")
## Automatically use showtext to render text for future devices
showtext_auto()

## use the ggplot2 example
sticker(p, package="PGM", p_size=22, s_x=1, s_y=.75, s_width=1.3, s_height=1,
        p_family = "gochi", filename="./PGM.png")
```

```{r}
imgurl <- system.file("figures/cat.png", package="hexSticker")
sticker(imgurl, package="hexSticker", p_size=20, s_x=1, s_y=.75, s_width=.6,
        filename="imgfile.png")
```

[hexSticker](https://github.com/GuangchuangYu/hexSticker)

# 方案二

[hexmake](https://connect.thinkr.fr/hexmake/)

[Owning a hex sticker](https://www.bioinfo-scrounger.com/archives/hex-sticker/)

# 方案三

[R script to neatly align hexagon stickers](https://github.com/mitchelloharawild/hexwall)

# 方案四

[How to generate a hex sticker with {openai} and {cropcircles}](https://www.r-bloggers.com/2023/06/how-to-generate-a-hex-sticker-with-openai-and-cropcircles/)

# 方案五

[stickr](https://github.com/akgold/stickr) - An R package to use RStudio Hex Stickers

```{r}
library(stickr)
stickr_get("tidyverse")
stickr_get("textmineR")
stickr_get("textmineR", filename = "textmineR_v8.png")
#if (interactive()) stickr_insert("R6")
```

# 其他

[Making a Hexagon Sticker](https://emitanaka.rbind.io/post/2018-04-hexsticker/)

[Arranging hex stickers in R](https://www.mitchelloharawild.com/blog/hexwall/)

[Tips on designing hex stickers for #rstats packages](https://zhuhao.org/post/tips-on-designing-a-hex-sticker-for-rstats-packages/)

[RStudio hex stickers](https://github.com/rstudio/hex-stickers)

[Tips on designing hex stickers for #rstats packages](https://zhuhao.org/post/tips-on-designing-a-hex-sticker-for-rstats-packages/)

[Rebranding R Packages with Hexagon Stickers: A Minimalist Approach](https://jianfengwu2022.github.io/blog/post/rebranding-r-packages-with-hexagon-stickers/)
