---
title: "reactablefmtr"
author: "zhly"
date: "2023-12-15"
categories: [r, code, table, visualization]
format: html
editor: visual
---

```{r setup, include=FALSE}
library(reactablefmtr)
library(reactable)
library(tidyverse)
library(viridis)
```

## title

```{r}
reactable(iris[10:29, ]) %>%
  add_title("This is a title") %>% 
  add_subtitle("This is a subtitle") %>% 
  add_source("This is a source")
```

## theme

```{r}
data <- MASS::Cars93[1:30, c("Model", "MPG.city", "MPG.highway")]

data %>%
  reactable(.,
    defaultColDef =
      colDef(
        cell = data_bars(., fill_color = viridis::mako(5), bar_height = 30)
  )
)
```

```{r}
#default theme
data %>%
  reactable(.,
    theme = default(centered = TRUE),
    defaultColDef =
      colDef(
        cell = data_bars(., fill_color = viridis::mako(5), bar_height = 30)
  )
)
```

```{r}
data %>%
  reactable(.,
    theme = slate(font_size = 18, header_font_size = 20, header_font_color = "darkorange", cell_padding = 8, font_color = "red"),#change theme
    defaultColDef =
      colDef(
        cell = data_bars(., fill_color = viridis::mako(5), text_position = "inside-end", background = "transparent")
  )
)
```

```{r}
data %>%
  reactable(.,
    theme = flatly(),
    defaultColDef =
      colDef(
        cell = data_bars(., fill_color = viridis::mako(5), text_position = "inside-end")
  )
)
```

```{r}
data %>%
  reactable(.,
    theme = cosmo(),
    defaultColDef =
      colDef(
        cell = data_bars(., fill_color = viridis::mako(5), text_position = "inside-end")
  )
)
```

## data bars

```{r}
data <- data.frame(
  Group = c("Red Group 1","Red Group 2","Red Group 3","Red Group 4","Red Group 5",
            "Blue Group 1","Blue Group 2","Blue Group 3","Blue Group 4","Blue Group 5",
            "Green Group 1","Green Group 2","Green Group 3","Green Group 4","Green Group 5"),
  Pct1 = c(.27, .82, .44, .68, .78, 
           .74, .66, .33, .23, .20, 
           .50, .55, .40, .70, .60),
  Pct2 = c(.33, .17, .87, .54, .37,
           .84, .72, .61, .48, .77,
           .21, .39, .60, .55, .81)
)
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     text_position = "outside-base", #change the location of the values
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     text_position = "inside-base", 
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data,
                     text_position = "inside-end",
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data,
                     text_position = "center", 
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data,
                     text_position = "above", 
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     text_position = "none")
  )
)
```

```{r}
#force_side
reactable(
  data,
  pagination = FALSE,
  defaultSortOrder = "desc",
  defaultSorted = "Pct2",
  defaultColDef = colDef(
    cell = data_bars(data, 
                     number_fmt = scales::percent,
                     force_outside = c(0,0.4))
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     align_bars = "right", #aligning data bars
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  columns = list(
    Pct1 = colDef(
      cell = data_bars(data, 
                       align_bars = "right", 
                       text_position = "inside-end", 
                       number_fmt = scales::percent)
      ),
    Pct2 = colDef(
      cell = data_bars(data, 
                       align_bars = "left",
                       text_position = "inside-end",
                       number_fmt = scales::percent)
      )
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     box_shadow = TRUE, 
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     round_edges = TRUE, 
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     border_style = "solid",
                     border_color = "gold", 
                     border_width = "2px",
                     number_fmt = scales::percent)
  )
)
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     fill_color = viridis(5), 
                     background = "lightgrey",
                     text_position = "inside-end", 
                     max_value = 1, 
                     number_fmt = scales::percent)
  )
)
```

```{r}
#increase bar height
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     bar_height = 35, 
                     number_fmt = scales::percent)
  )
)
```

```{r}
#decrease bar height
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data,
                     bar_height = 3, 
                     text_position = "outside-end", 
                     background = "transparent", 
                     number_fmt = scales::percent)
  )
)
```

```{r}
data %>%
  mutate(color_pal = case_when(
    str_detect(Group, "Red") ~ "#FF3B28",
    str_detect(Group, "Blue") ~ "#006FEF",
    str_detect(Group, "Green") ~ "#3ABC0E",
    TRUE ~ "darkgrey"
  )) %>%
reactable(.,
  pagination = TRUE,#分页
  defaultColDef = colDef(
    cell = data_bars(.,
                     fill_color_ref = "color_pal", 
                     text_position = "inside-end",
                     background = "lightgrey", 
                     max_value = 1, 
                     number_fmt = scales::percent)
  ),
  columns = list(color_pal = colDef(show = FALSE) ## hide the color_pal column
  )
) 
```

```{r}
reactable(
  data,
  pagination = FALSE,
  defaultColDef = colDef(
    cell = data_bars(data, 
                     fill_color = c("#1efffd", "#1e20ff"), 
                     fill_gradient = TRUE, 
                     background = "lightgrey", 
                     max_value = 1, 
                     brighten_text = FALSE,
                     text_color = "white",
                     number_fmt = scales::percent)
  )
)
```

```{r}
#only works with columns of character-type, not for factors
car_data <- MASS::Cars93 %>% 
  filter(Type %in% c('Compact', 'Sporty', 'Van')) %>% 
  select(c('Make', 'Type', 'MPG.city')) %>% 
  mutate(Make = as.character(Make)) %>% 
  tail(10)

reactable(
  car_data,
  columns = list(
    Make = colDef(
      cell = data_bars(car_data, fill_by = "MPG.city", text_position = "above")
    )
  )
)
```

## legend

```{r}
reactable(
  car_data,
  defaultSorted = "MPG.city",
  defaultSortOrder = "desc",
  columns = list(
    Make = colDef(
      cell = data_bars(car_data, fill_by = "MPG.city", text_position = "above", fill_color = c("#22577A","#38A3A5","#57CC99","#80ED99","#C7F9CC"))
    )
  )
) %>% 
add_legend(car_data, col_name = 'MPG.city', title = 'MPG City', align = 'left', colors = c("#22577A","#38A3A5","#57CC99","#80ED99","#C7F9CC"))
```

```{r}
data %>% 
  mutate(Change = Pct1 - Pct2) %>% 
  select(Group, Change) %>% 
reactable(.,
  pagination = FALSE,
  columns = list(
    Change = colDef(
      cell = data_bars(., 
                       fill_color = c("lightblue","orange"),
                       number_fmt = scales::percent))
  )
)
```

```{r}
data %>% 
  mutate(Change = Pct1 - Pct2) %>% 
  select(Group, Change) %>% 
reactable(.,
  pagination = FALSE,
  defaultSorted = "Change",
  defaultSortOrder = "asc",
  columns = list(
    Change = colDef(
      cell = data_bars(., 
                       fill_color = c("lightblue","orange"),
                       text_position = "inside-end", 
                       number_fmt = scales::percent))
  )
)
```

## icon

```{r}
data <- data.frame(
  Company = c("facebook", "twitter", "linkedin", "reddit", "youtube", "instagram", "pinterest", "snapchat"),
  Primary = c("#4267B2", "#1DA1F2", "#0E76A8", "#FF4500", "#FF0000", "#833AB4", "#E60023", "#FFFC00"),
  Values = c(75, 120, 90, 100, 80, 70, 60, 40)
)
reactable(
  data,
  defaultSorted = "Values",
  defaultSortOrder = "desc",
  columns = list(
    Values = colDef(
      cell = data_bars(data, 
                       icon_ref = "Company", #add icon
                       icon_color_ref = "Primary",
                       fill_color = "black",
                       fill_opacity = 0.8, 
                       text_position = "inside-end"))
  )
)
```

```{r}
reactable(
  data,
  defaultSorted = "Values",
  defaultSortOrder = "desc",
  columns = list(
    Values = colDef(
      cell = data_bars(data, 
                       icon_ref = "Company",
                       icon_size = 35,
                       fill_color_ref = "Primary",
                       background = "transparent",
                       text_position = "inside-end"))
  )
)
```

未完待续。。。。

[Learn more](https://kcuilla.github.io/reactablefmtr/articles/data_bars.html)
